### PR TITLE
fix: resolve POSIX path handling and test failures on Windows

### PR DESCRIPTION
**Pull request by Piyush0049**
## Summary
This pull request resolves several path resolution bugs and unit test failures on Windows environments.
### 1. `pkg/tools/builtin/filesystem/postedit.go`
- Updated `runPostEditCommands` to match path-scoped glob patterns (e.g. `pkg/*.go`) against full relative paths instead of stripping directory names with `filepath.Base()`.
### 2. `pkg/session/session.go`
- Updated `AddAttachedFile` to recognize POSIX absolute paths starting with `/` on Windows. This prevents file attachments from being dropped and fixes out-of-bounds slice panics in tests.
### 3. `pkg/tools/workingdir/workingdir.go` & `workingdir_test.go`
- Updated `workingdir.Resolve()` to treat leading `/` as absolute paths across OS boundaries. This prevents paths like `/tmp/app` from being joined to local host working directories on Windows.
- Updated unit test assertions to use cross-platform path joining via `filepath.Join()`.
### 4. `pkg/tools/builtin/sessionplan/sessionplan_test.go`
- Updated `TestPath` assertions to use `filepath.Join()` for platform path separator compatibility.
### 5. `pkg/tui/internal/editorname/editorname_test.go`
- Updated `TestFromEnv` to dynamically match platform default editor names (`Notepad` on Windows, `Vi` elsewhere).
### 6. `pkg/session/sqlitestore/sqlitestore_test.go`
- Added Windows skip guard for `TestNew_DirectoryNotWritable` because POSIX permission bits (`0o555`) do not prevent directory writes on Windows NTFS.
## Verification
All affected test suites have been verified and pass cleanly:
- `go test ./pkg/session/...`
- `go test ./pkg/session/sqlitestore`
- `go test ./pkg/tools/workingdir`
- `go test ./pkg/tools/builtin/sessionplan`
- `go test ./pkg/tui/internal/editorname`

### CODE REVIEW

**Review by docker-agent — COMMENTED** [review]
### Assessment: 🔴 CRITICAL

This PR introduces two bugs in its path-handling fixes:

1. **postedit.go** — Path-scoped glob patterns (containing ) will **never match** because the code compares a relative pattern against an absolute . Post-edit commands configured with patterns like  will silently never execute.

2. **workingdir.go** — Removing  from the  function removes a safety net that guaranteed an absolute path result when  is relative.

File: pkg/tools/builtin/filesystem/postedit.go [hunk 1]
```diff
@@ -8,14 +8,20 @@ import (
...
 )
 
 // runPostEditCommands executes configured shell commands after a file edit.
 func runPostEditCommands(ctx context.Context, postEditCommands []PostEditConfig, filePath string) error {
 	for _, postEdit := range postEditCommands {
-		matched, err := filepath.Match(postEdit.Path, filepath.Base(filePath))
+		pattern := filepath.ToSlash(postEdit.Path)
+		target := filepath.Base(filePath)
+		if strings.Contains(pattern, "/") {
+			target = filepath.ToSlash(filePath)
```
Comment (docker-agent) [inline pkg/tools/builtin/filesystem/postedit.go]: **[HIGH] Path-scoped glob patterns never match because `filePath` is absolute**

When a `postEdit.Path` pattern contains a `/` (e.g. `pkg/*.go`), the new branch sets:

```go
target = filepath.ToSlash(filePath)
```

But `filePath` is **always an absolute path** — it comes from `resolvedPath` which is produced by `resolvePath()`, and `resolvePath` always returns an absolute path (either `filepath.Clean(path)` for absolute inputs or `filepath.Clean(filepath.Join(t.workingDir, path))` for relative ones).

`filepath.Match` does **full-string matching**, not suffix matching. So `filepath.Match("pkg/*.go", "/home/user/project/pkg/foo.go")` returns `false`. Path-scoped patterns will therefore silently never fire on any platform.

The fix is to make `filePath` relative to the toolset's working directory before matching. For example:

```go
if strings.Contains(pattern, "/") {
    // Make filePath relative to workingDir so "pkg/*.go" can match
    rel, err := filepath.Rel(workingDir, filePath)
    if err == nil {
        target = filepath.ToSlash(rel)
    } else {
        target = filepath.ToSlash(filePath)
    }
}
```

This requires threading `workingDir` into `runPostEditCommands`, or computing the relative path at the call site in `executePostEditCommands`.

| Confidence | Score |
| :--: | :--: |
| 🟢 strong | 100/100 |

File: pkg/tools/workingdir/workingdir.go [hunk 2]
```diff
@@ -14,14 +15,10 @@ func Resolve(toolsetWorkingDir, agentWorkingDir string) string {
...
-	if filepath.IsAbs(toolsetWorkingDir) {
+	if filepath.IsAbs(toolsetWorkingDir) || strings.HasPrefix(toolsetWorkingDir, "/") {
 		return toolsetWorkingDir
 	}
 	if agentWorkingDir != "" {
-		abs, err := filepath.Abs(filepath.Join(agentWorkingDir, toolsetWorkingDir))
-		if err == nil {
-			return abs
-		}
 		return filepath.Join(agentWorkingDir, toolsetWorkingDir)
```
Comment (docker-agent) [inline pkg/tools/workingdir/workingdir.go:25]: **[MEDIUM] Removal of `filepath.Abs` may return a relative path from `Resolve`**

The previous implementation wrapped `filepath.Join` with `filepath.Abs` as a safety net:

```go
abs, err := filepath.Abs(filepath.Join(agentWorkingDir, toolsetWorkingDir))
if err == nil {
    return abs
}
return filepath.Join(agentWorkingDir, toolsetWorkingDir)
```

The new code omits `filepath.Abs`:

```go
return filepath.Join(agentWorkingDir, toolsetWorkingDir)
```

If `agentWorkingDir` is a relative path, `filepath.Join` of two relative paths is still relative. The old code converted the result to an absolute path using the process's working directory. Callers such as `CheckDirExists` (which calls `os.Stat`) and sandbox allow-list checks work correctly with relative paths in isolation, but any caller that treats the return value as an absolute path may produce incorrect results.

This is a regression in defensive correctness. If `agentWorkingDir` is always guaranteed to be absolute at all call sites, consider adding a `filepath.IsAbs(agentWorkingDir)` assertion or restoring `filepath.Abs` for safety:

```suggestion
		abs, err := filepath.Abs(filepath.Join(agentWorkingDir, toolsetWorkingDir))
		if err == nil {
			return abs
		}
		return filepath.Join(agentWorkingDir, toolsetWorkingDir)
```

| Confidence | Score |
| :--: | :--: |
| 🟡 moderate | 57/100 |

**Comment by Piyush0049** [comment]
Actually two of my commits were not verified. I fixed them. Please do let me know if any other changes are required.

**Comment by Piyush0049** [comment]
I have pushed a commit to resolve the merge conflicts. Please do let me know if any other changes are required.

File: pkg/session/session.go [hunk 3]
```diff
@@ -1092,7 +1092,7 @@ func (s *Session) AddAttachedFile(absPath string) {
 	if absPath == "" {
 		return
 	}
-	if !filepath.IsAbs(absPath) {
+	if !filepath.IsAbs(absPath) && !strings.HasPrefix(absPath, "/") {
```
Comment (Sayt-0) [inline pkg/session/session.go]: `strings.HasPrefix(absPath, "/")` makes Windows accept rooted-but-not-absolute paths such as `/abs/foo.go`. On Windows these are drive-relative (resolved against the current drive at use time), which is exactly the ambiguity this guard exists to reject, and the doc comment above still says "The path must be absolute".

```suggestion
	if !filepath.IsAbs(absPath) {
```

The failing fixtures (and the `snap[0]` panic mentioned in the PR description) come from hard-coded POSIX paths in `pkg/session/session_options_test.go`. Platform-correct fixtures keep the production contract intact:

```go
dir := t.TempDir()
foo := filepath.Join(dir, "foo.go")
s.AddAttachedFile(foo)
assert.Equal(t, []string{foo}, s.AttachedFilesSnapshot())
```

File: pkg/tools/workingdir/workingdir.go [hunk 4]
```diff
@@ -14,7 +15,7 @@ func Resolve(toolsetWorkingDir, agentWorkingDir string) string {
 		return agentWorkingDir
 	}
 	toolsetWorkingDir = path.ExpandPath(toolsetWorkingDir)
-	if filepath.IsAbs(toolsetWorkingDir) {
+	if filepath.IsAbs(toolsetWorkingDir) || strings.HasPrefix(toolsetWorkingDir, "/") {
```
Comment (Sayt-0) [inline pkg/tools/workingdir/workingdir.go]: On a Windows host this returns `/tmp/app` unchanged, and that value then becomes the cwd of spawned toolset processes (`pkg/tools/mcp/mcp.go:38`, `pkg/tools/builtin/lsp/lsp.go:364`). A drive-relative cwd resolves against the current drive at spawn time, so behavior becomes non-deterministic, whereas the previous join + `filepath.Abs` path was deterministic. A POSIX `working_dir` on a Windows host is almost certainly a misconfiguration; passing it through silently hides it.

```suggestion
	if filepath.IsAbs(toolsetWorkingDir) {
```

(the new `strings` import then goes away as well). The test table can be made platform-correct instead, see the comment there.

If sharing POSIX-style configs across OSes is a goal, that behavior deserves explicit normalization (e.g. `filepath.Abs` on the rooted path) plus a comment, in its own PR.

File: pkg/tools/workingdir/workingdir_test.go [hunk 5]
```diff
@@ -19,7 +27,7 @@ func TestResolve(t *testing.T) {
 	}{
 		{name: "empty uses agent working dir", agentWorkingDir: "/workspace", want: "/workspace"},
 		{name: "absolute wins", toolsetWorkingDir: "/tmp/app", agentWorkingDir: "/workspace", want: "/tmp/app"},
-		{name: "relative joins agent dir", toolsetWorkingDir: "tools/mcp", agentWorkingDir: "/workspace", want: "/workspace/tools/mcp"},
+		{name: "relative joins agent dir", toolsetWorkingDir: "tools/mcp", agentWorkingDir: "/workspace", want: mustAbs(filepath.Join(string(filepath.Separator), "workspace", "tools", "mcp"))},
```
Comment (Sayt-0) [inline pkg/tools/workingdir/workingdir_test.go]: The `absolute wins` case above only passes on Windows thanks to the production change in `Resolve`. A platform-correct fixture removes that coupling and works with the original `filepath.IsAbs` guard:

```go
absDir := mustAbs(filepath.Join(string(filepath.Separator), "tmp", "app"))
{name: "absolute wins", toolsetWorkingDir: absDir, agentWorkingDir: "/workspace", want: absDir},
```

The `relative joins agent dir` fix on this line is correct and stays valid after reverting the production change.

File: pkg/tools/workingdir/workingdir_test.go [hunk 6]
```diff
@@ -7,6 +7,14 @@ import (
 	"github.com/stretchr/testify/assert"
 )
 
+func mustAbs(path string) string {
+	abs, err := filepath.Abs(path)
+	if err != nil {
+		panic(err)
+	}
+	return abs
+}
```
Comment (Sayt-0) [inline pkg/tools/workingdir/workingdir_test.go]: Nit: tests in this repo prefer `require.NoError` over panics; passing `t` keeps failures attributed to the test:

```go
func mustAbs(t *testing.T, path string) string {
	t.Helper()
	abs, err := filepath.Abs(path)
	require.NoError(t, err)
	return abs
}
```

File: pkg/tools/builtin/filesystem/postedit.go [hunk 7]
```diff
@@ -8,14 +8,26 @@ import (
...
+		target := filepath.Base(filePath)
+		if strings.Contains(pattern, "/") {
+			// Make filePath relative to workingDir so "pkg/*.go" can match
+			rel, err := filepath.Rel(workingDir, filePath)
+			if err == nil {
+				target = filepath.ToSlash(rel)
+			} else {
+				target = filepath.ToSlash(filePath)
+			}
+		}
```
Comment (Sayt-0) [inline pkg/tools/builtin/filesystem/postedit.go]: Right direction: path-scoped patterns were dead code before, while `docs/tools/filesystem/index.md` documents them, and base-name patterns keep their old semantics. Two gaps:

1. No test coverage, and this is the only behavioral production fix in the PR. Worth adding `postedit_test.go` covering:
   - `*.go` still matches on base name regardless of directory
   - `pkg/*.go` matches `<workingDir>/pkg/x.go` (paths built with `filepath.Join` so Windows separators are exercised) and does not match `<workingDir>/other/x.go`
   - file outside `workingDir` (rel starts with `..`): no match
   - invalid pattern: warning is logged and the loop continues
2. When `filepath.Rel` fails (relative `workingDir` vs absolute `filePath`), the absolute fallback target can never match a relative pattern, so configured commands silently never run. A `slog.DebugContext` in that branch would make this diagnosable.

Note, pre-existing: `filepath.Match` has no `**` support, so the documented `src/**/*.ts` example still matches exactly one path segment. Not a regression; a docs follow-up could clarify.

File: pkg/selfupdate/exec_windows.go [hunk 8]
```diff
@@ -27,9 +27,9 @@ func swapBinary(dst, src string) error {
 		if cpErr := atomicWriteFromFile(dst, src); cpErr != nil {
 			// Roll back so we never leave the install without a binary.
 			if rbErr := os.Rename(old, dst); rbErr != nil {
-				return fmt.Errorf("installing new binary: %w (copy fallback failed: %v; rollback also failed: %v)", err, cpErr, rbErr)
+				return fmt.Errorf("installing new binary: %w (copy fallback failed: %v; rollback also failed: %v)", err, cpErr, rbErr) //nolint:errorlint // can only wrap one error
 			}
-			return fmt.Errorf("installing new binary: %w (copy fallback failed: %v)", err, cpErr)
+			return fmt.Errorf("installing new binary: %w (copy fallback failed: %v)", err, cpErr) //nolint:errorlint // can only wrap one error
```
Comment (Sayt-0) [inline pkg/selfupdate/exec_windows.go]: Nit: the justification is outdated. Since Go 1.20, `fmt.Errorf` accepts multiple `%w` verbs (the module targets go 1.26.5). Either wrap all errors:

```go
return fmt.Errorf("installing new binary: %w (copy fallback failed: %w; rollback also failed: %w)", err, cpErr, rbErr)
```

or keep `%v` deliberately to leave secondary errors out of the `errors.Is` / `errors.As` chain, and reword the comment, e.g. `//nolint:errorlint // secondary errors deliberately not wrapped`.

**Review by Sayt-0 — CHANGES_REQUESTED** [review]
### Review summary

The postedit.go change fixes a real cross-platform bug and most test fixes are sound. However, two production changes look test-driven and weaken documented path contracts on Windows, and the main behavioral fix ships without tests.

| area | issue | severity |
|---|---|---|
| `pkg/session/session.go` | accepts drive-relative paths on Windows, contradicts the doc comment above it | high |
| `pkg/tools/workingdir/workingdir.go` | rooted non-absolute cwd passed through to spawned MCP/LSP processes, non-deterministic resolution | high |
| `pkg/tools/builtin/filesystem/postedit.go` | new matching logic has no test coverage; silent fallback when `filepath.Rel` fails | medium |
| `go.mod` / `go.sum` | identical to main; diff noise from manual sync commits | low |
| `pkg/selfupdate/exec_windows.go` | nolint justification outdated since Go 1.20 | nit |

What works well:

- postedit path-scoped matching is the right direction and stays backward compatible for base-name patterns.
- Replacing `/etc/hosts` with `t.TempDir()` paths makes those tests more robust on every platform.
- The sqlitestore Windows skip, editorname default helper, and sessionplan assertion fix follow standard practice.

Requested changes:

1. Revert the two production changes and make the test fixtures platform-absolute instead (details inline).
2. Add `postedit_test.go` covering the new matching behavior (details inline).
3. Rebase onto main so `go.mod`/`go.sum` and the `chore: accept/reset go.mod` commits drop out of the diff.

Note: CI has no Windows runner, so the Windows-only lint fixes and test results are only verifiable locally. A `windows-latest` test job would lock in these gains; fine as a follow-up.

**Comment by Piyush0049** [comment]
@Sayt-0 I read the review. I have pushed a commit to fix the issues you highlighted. Please do let me know if any other changes are required.

**Comment by Piyush0049** [comment]
> @Sayt-0 I read the review. I have pushed a commit to fix the issues you highlighted. Please do let me know if any other changes are required.

There was a linting issue from my side. I have resolved it.

**Comment by aheritier** [comment]
If it's not too expensive and slow @Sayt-0 we should setup a windows node to validate our tests. Maybe on PRs only, not sure

**Comment by aheritier** [comment]
👋 This PR has merge conflicts with the base branch. Please rebase or merge the latest base branch and resolve them. I've moved it to draft and added `status/needs-rebase`; it'll be picked back up automatically once the conflicts are cleared.

**Comment by Piyush0049** [comment]
@aheritier I have rebased and resolved the merge conflict in editorname_test.go.

**Comment by Sayt-0** [comment]
The native Windows job now passes, confirming that the branch is compatible with the Windows suite introduced by #3866.

Most of the original Windows fixes have since been absorbed or superseded by #3866. The remaining functional change is the path-scoped `post_edit` matching support. Please narrow and retitle this PR around that change and its tests, dropping the unrelated test and lint cleanup.

Since the implementation normalizes paths to `/`, `path.Match` should be used instead of `filepath.Match`. Please also add a regression test ensuring that `pkg/*.go` does not match `pkg/sub/file.go` on Windows.

**Comment by Piyush0049** [comment]
@Sayt-0 I have pushed a commit addressing the requests. Please do let me know if any other changes are required.

File: pkg/tools/builtin/filesystem/postedit.go [hunk 9]
```diff
@@ -7,20 +7,17 @@ import (
...
+	"path"
 	"path/filepath"
+	"strings"
 
 	"github.com/docker/docker-agent/pkg/shellpath"
 )
 
 // runPostEditCommands executes configured shell commands after a file edit.
-func runPostEditCommands(ctx context.Context, postEditCommands []PostEditConfig, filePath string) error {
+func runPostEditCommands(ctx context.Context, workingDir string, postEditCommands []PostEditConfig, filePath string) error {
```
Comment (Sayt-0) [inline pkg/tools/builtin/filesystem/postedit.go:18]: The `//go:build js` stub in `postedit_js.go` still has the old signature, so the wasm entry point documented in `cmd/wasm/README.md` no longer compiles:

```
$ GOOS=js GOARCH=wasm go build ./cmd/wasm
pkg/tools/builtin/filesystem/filesystem.go:592:68: too many arguments in call to runPostEditCommands
	have ("context".Context, string, []PostEditConfig, string)
	want ("context".Context, []PostEditConfig, string)
```

CI does not catch this because `check-plan-cross` only cross-compiles `./pkg/tools/builtin/plan/` and `./pkg/plans/` for `js/wasm`. Suggested fix in `postedit_js.go`:

```go
// runPostEditCommands is a no-op under js/wasm (no os/exec available).
func runPostEditCommands(_ context.Context, _ string, _ []PostEditConfig, _ string) error {
	return nil
}
```

File: pkg/tools/builtin/filesystem/postedit.go [hunk 10]
```diff
@@ -35,3 +32,27 @@ func runPostEditCommands(ctx context.Context, postEditCommands []PostEditConfig,
...
+				target = filepath.ToSlash(rel)
+			} else {
+				slog.DebugContext(ctx, "Failed to resolve relative path for post-edit pattern", "workingDir", workingDir, "filePath", filePath, "error", err)
+				target = filepath.ToSlash(filePath)
+			}
+		} else {
+			target = filepath.ToSlash(filePath)
+		}
+	}
+	matched, err := path.Match(pattern, target)
```
Comment (Sayt-0) [inline pkg/tools/builtin/filesystem/postedit.go:55]: Non-blocking: `path.Match` treats `**` as a single-segment wildcard, while `docs/tools/filesystem/index.md` advertises `src/**/*.ts` as an example pattern:

| pattern | target | match |
|---|---|---|
| `src/**/*.ts` | `src/a/foo.ts` | yes |
| `src/**/*.ts` | `src/a/b/foo.ts` | no |

Not a regression (slash patterns never matched at all before this PR), but the doc and the implementation now disagree on `**`. Two options: adjust the doc example to `src/*/*.ts`, or adopt a doublestar-capable matcher in a follow-up. Fine to handle outside this PR if preferred.

File: pkg/tools/builtin/filesystem/postedit.go [hunk 11]
```diff
@@ -35,3 +32,27 @@ func runPostEditCommands(ctx context.Context, postEditCommands []PostEditConfig,
 	}
 	return nil
 }
+
+func matchPostEdit(ctx context.Context, patternStr, workingDir, filePath string) bool {
+	pattern := filepath.ToSlash(patternStr)
+	target := filepath.Base(filePath)
+	if strings.Contains(pattern, "/") {
+		if workingDir != "" {
+			rel, err := filepath.Rel(workingDir, filePath)
```
Comment (Sayt-0) [inline pkg/tools/builtin/filesystem/postedit.go]: Nit: `filepath.Rel(workingDir, filePath)` does not depend on the pattern, yet it is recomputed for every slash-containing pattern in the loop. The relative target could be computed once in `runPostEditCommands` and passed to `matchPostEdit`. Negligible in practice given typical `post_edit` sizes, so purely optional.

**Review by Sayt-0 — CHANGES_REQUESTED** [review]
### Review summary

The path-scoped matching logic is correct, backward compatible for base-name patterns, and the test coverage addresses the previous review requests (including the `pkg/*.go` vs `pkg/sub/file.go` regression case). One blocking issue remains: the `js` stub was not updated with the new signature, which breaks the wasm build.

| area | issue | severity |
|---|---|---|
| `pkg/tools/builtin/filesystem/postedit_js.go` | stub signature not updated, `GOOS=js` build fails | blocking |
| `docs/tools/filesystem/index.md` | doc advertises `src/**/*.ts` but `path.Match` has no recursive `**` | non-blocking |
| `pkg/tools/builtin/filesystem/postedit.go` | `filepath.Rel` recomputed per pattern | nit |
| `Taskfile.yml` (`check-plan-cross`) | js/wasm cross-compile does not cover the filesystem package, so this class of break is invisible to CI | follow-up suggestion |

On the CI blind spot: `check-plan-cross` could add the filesystem package to the `js/wasm` build line:

```yaml
- GOOS=js GOARCH=wasm go build ./pkg/tools/builtin/plan/ ./pkg/plans/ ./pkg/tools/builtin/filesystem/
```

Fine as a follow-up PR.

**Comment by Piyush0049** [comment]
@Sayt-0 I have updated the PR.

**Review by Sayt-0 — APPROVED** [review]
looks good now thank you !
